### ISSUE TITLE
Using on non wordpress images

### ISSUE THREAD

**Issue by rgfx** [aderaaij/wp-image-preload#1]
Thanks for the plugin works great. I have a landing page with some images, not from the WordPress media gallery. Can I use your code somehow to lazyload those images? 

Like with a class if possible...

Please advise.

**Comment by rgfx** [comment]
change src to data-src everything worked. Sorry about that.

**Comment by aderaaij** [comment]
No problem, glad you enjoy the plugin and you got everything working!
