### ISSUE TITLE
Working with ajax. 

### ISSUE THREAD

**Issue by rgfx** [aderaaij/wp-image-preload#2]
I using a plugin facetwp to filter some post. They use ajax to sort, when it's called the images no longer appear. is-loaded and data-loaded are removed.  

My attempt below doesn't seem to work, an suggestions? 

```javascript
$(document).on("facetwp-refresh", function() {
    const observer = preLoad("img[data-src]", {
      threshold: 0.1,
      rootMargin: "0px"
    });
    observer.observe();
  });
```
Thanks

**Comment by aderaaij** [comment]
Hey there! Try replacing `facetwp-refresh` with `facetwp-loaded` loaded. According to the docs `facetwp-refresh` is applied before content is refresh, while `facetwp-loaded` gets called when the refresh is finished: https://facetwp.com/documentation/facetwp-loaded/.

**Comment by rgfx** [comment]
yo, thanks for the quick reply. 

I tried facetwp-loaded before as well.  The weird thing is everything works  on the archive page but not the categories... Even though the code is the same. 

Also fires fine the first time, but once I click on a filter loaded is removed.

**Comment by aderaaij** [comment]
Interesting. I'm guessing there's something removing data attributes from images in the facetwp script, although that wouldn't make too much sense. Do you get any error messages?

Also, I came across a bunch of files for facetwp, linked from their docs page. Have you tried anything like this: 

```javascript
 $(document).on('facetwp-refresh', function() {
        if (! FWP.loaded) {
            FWP.loading_handler = function(params) {
                // do something
            }
        }
    });
})(jQuery);
```
I'm not sure if it helps but it might be worth a try. More scripts here: https://gist.github.com/search?utf8=%E2%9C%93&q=user%3Amgibbs189+facetwp-refresh

Other than that I'm not yet sure what the culprit is. Unfortunately I can't try the plugin out myself as it's not open source.

**Comment by rgfx** [comment]
Bummer,

I found this https://gist.github.com/mgibbs189/af2bf17c240bf3241d9eb5829bd6a4fa

```php
add_action('wp_head', function () {

    echo '<script>const observer=preLoad("img[data-src]",{threshold:.1,rootMargin:"0px"});observer.observe();</script>';

}, 100);
```

Threw a error "preLoad is not defined" This maybe because the plugin is loaded after. Tried increasing delay no luck. 

But am calling the lazy-load correctly right?

**Comment by aderaaij** [comment]
Yeah you're calling the lazyload correctly alright, that shouldn't be the problem. In your example here you miss the facetwp part of the script though, so it should be something like

```html
<?php
add_action( 'wp_head', function() {
?>
<script>
(function($) {
  $(document).on('facetwp-loaded', function() {
    const observer = preLoad("img[data-src]", {
      threshold: 0.1,
      rootMargin: "0px"
    });
    observer.observe();
  });
})(jQuery);
</script>
<?php
}, 100 );
```

**Comment by rgfx** [comment]
Woops, good catch. 

Thanks for all your help, somehow it works now. Tried for 30 minutes to replicate the issue, with no luck. Maybe something to do with caching. 

Weird.

**Comment by aderaaij** [comment]
I like self-solving problems! Hope it stays that way. If you ever find out what it was, don't hesitate to update this issue for future reference! Thanks
