### ISSUE TITLE
Change secret images on resize. 

### ISSUE THREAD

**Issue by rgfx** [aderaaij/wp-image-preload#3]
Hey pal, it's me again. 

Nothing wrong with your plugin, as usual, I just wanted to run something by you. Hoping you have a solution or can push me in the right direction. 

Working on "hero image" system.  I want to use a different aspect ratio depending if you're using mobile or desktop. The plan is to use ACF with a cropping tool force an aspect ratio. Would like to use srcset or in our case data-src to lazyload. 

Most just use a background-size: cover; call it day. They don't care about efficiency, load a 2000px width image on 400px wide screen. They probably even use a page builder, or worse yet, make more money than me :)

My issue is the with scrset. If you notice, the image gets rendered on first load and never again. If you resize your browser you will notice the same image being used.  This breaks the layout when someone switches to landscape mode or vise versa. Is there a way to fire srcset again?

What approach would you take, what do you do? Lozad has background lazyload feature, but is not responsive. Am I the only one that cares?

I made a pen with your script, I added a throttle resize function to fire when resize is complete. You should see the issue. 

https://codepen.io/rgfx/pen/XzOgyq

let me know, thanks.

**Comment by aderaaij** [comment]
Hey mate! That's an interesting issue and I don't know what's the best solution. To give a proper answer I guess I'd have to ask you what it is exactly you need. Is it about a single hero image? (and if so, does it really need to be lazyloaded?) or is it a list of hero images that indeed needs to be lazyloaded? Also, does the image has any semantic value? So should it be an actual `img` (and maybe use css `object-fit`) or should it be a background image, or is it not that important either way?

A few thoughts about `srcset`:

`srcset` is all about letting the browser chose the optimized image available in the srcset, and the browsers all show different behaviour. I did some tests with this demo: http://srcset.salcode.com/ and came to the following conclusions on resizing and using `srcset`. 
* **Firefox**: When resizing from small to large and from large to small, Firefox loads the appropriate images. It will download lower resolution images even when there's already a larger image downloaded.
* **Chrome & Safari**: When resizing from large to small, it keeps the largest image and doesn't download any smaller images. When resizing from small to large, it will download bigger sized images.
All these results are on OSX High Sierra and with the latest stable versions of the browsers. 

So if you want total control over the result of which image is loaded `srcset` might not be the right choice. But if the layout is your main concern and you do trust browsers enough to take the right pick,  you could perhaps use the css `object-fit` property. The `object-fit` property lets your normal image have the same behavior as a background image so you can use it to cover an area with `object-fit: cover;` and define  the sizes of that area in normal media queries. There is an `object-fit` polyfill available, I don't know how good it works.

This wouldn't be reliable if you want to show images that are actually cropped in different aspect ratios. 

If you want to use background-images and combine that with lazyloading, you'd need to adapt the script a bit and make use of `matchmedia`. I guess you would have to add some custom `data-attributes` to your element. Like `<div data-small='image_small.jpg' data-medium='image_medium.jpg' data-large='image_large.jpg'`></div>`

and in the `preload.js`, replace ```element.style.backgroundImage = `url(${element.dataset.src})`;``` with some matchmedia queries. Then you still need to find a place where you can trigger the resize. I'd have to look for that. 

The funny thing is, I just noticed I've been doing this wrong on one of my sites, it actually loads two images on every occasion, so I need to look in to this as well. Let me know what it is exactly what you need and let's see if we can come up with something good!

**Comment by rgfx** [comment]
Thanks for caring man, means a lot to me.  Should be thinking about both a slider and single image. 

Currently using a library called [Flickity](https://github.com/metafizzy/flickity/).  It has lazyload built in, however someday I hope to roll my own. Love the swipe physics 

For now, the mission is single.  Thinking further should allow our clients to pick the height sometimes if they want.  Found this [ACF Plugin](https://wordpress.org/plugins/acf-image-crop-add-on/) to do the cropping.  To constrain aspect ratio, just in case. 

hence, my first pen is the ideal situation.  No need for object-fit or padding aspect ratio hack. But has the issues previously discussed.
https://codepen.io/rgfx/pen/rYPRPJ?editors=1100

This second pen works but we lose flexibility, seo, fade-in(unless we make it a child, absolute position) Doesn't feel right.  

The script has a cool regex function and also gives insights on using `data-attributes` with `matchmedia`   **Note:** I have `preload.js`  externally loaded into the pen. 
https://codepen.io/rgfx/pen/rYPbdo/

What do you think?

**Comment by aderaaij** [comment]
For sure! I think these are problems a lot of developers face and I hope we'll both be wiser when we've got a solution. 

The second pen is pretty smart! I like the data-attribute with media query idea. But I get the limitations of the background-image. Basically you always need to define the aspect ratio yourself, and unless you add some extra conditionals with ACF which the user must control.

What I'd think, is that you could apply the technique from the second pen to a normal image. So don't use `srcset`, use your own data-attributes and replace the `src` based on screen size. This way the size can still be decided on the image dimensions. Or so I think!

**Comment by rgfx** [comment]
Yeah that's what I was alluding to, I wonder if it will lazyload? Make my own `data att` then replace `data-src` and then call `observer.observe()` again.

I really don't like the idea of the image slowing down first paint.

**Comment by aderaaij** [comment]
If it's really a hero image, as in first image on the page, I'd imagine you'd want it to paint first. In that case you also wouldn't need the Intersection Observer but you'd trigger the change of image only with `window.resize` and the `matchmedia` queries. If you don't want an ugly repaint on first load and resizing you can always make use of this loading technique:

```javascript
const imgLoad = new Image();
            imgLoad.onload = () => {
                // add class or do something when image is loaded for nice fadein
            };
imgLoad.src = element.currentSrc;
```

**Comment by rgfx** [comment]
Yo,

https://codepen.io/rgfx/pen/zPbJra 

The alternative is using picturefill which is 1741 lines of code :)

Let me know if see any issues, or way to make it better.

**Comment by aderaaij** [comment]
Hey @rgfx, looks good! I think this is the way to go for now. Maybe when I have this problem again in the future I'll have a look on how to improve on this. For now I'll keep a reference to your Pen! 

Sorry for the late reply by the way, I've been experimenting with [Gatsby](https://www.gatsbyjs.org/) and having way too much fun with it. It's a static site generator based on React.

Also, do you know the site https://dev.to? I think you'd enjoy it!

I'll close this issue for now, thanks for your ideas and contributions!
